# Configuration file for the pwntter database
db:
    type:       mysql
    host:       server
    port:       3306
    database:   twitter 
    user:       user
    password:   password

output:
    json:
        jsonp:      yes
        callback:   'myCallback'
    html:
#        template:  myTemplate.html

stats:
    general:
        print:      yes

    clients:
        print:      yes
        minimum:    20

    busiest:
        print:      yes
        number:     20

    hashtags:
        print:      yes
        number:     20
        cloud:      50
        bannedtags: 'bannedtags.txt'

    words:
        print:      yes
        number:     20
        cloud:      50
        stopwords:  'stopwords.txt'